/**
 * OrderService — handles order creation, file generation, and storage upload.
 */
import { supabase } from "@/integrations/supabase/client";
import { generatePrintFile, parseDimensions, type PrintFileOptions } from "./printFileGenerator";
import { processVectorPdf } from "./vectorPdfProcessor";
import { generateOrderFormPDF, type OrderFormData } from "./orderFormGenerator";

export interface CreateOrderInput {
  customerName: string;
  customerEmail?: string;
  customerPhone: string;
  shippingAddress: string;
  designId?: string;
  designName: string;
  designImageSrc: string;
  dimensionLabel: string;
  quantity: number;
  unitPrice: number;
  isCustomDesign: boolean;
  customText?: string;
  customFont?: string;
  customTextAlign?: string;
  /** URL to original vector PDF — used directly as print file when available */
  sourcePdfUrl?: string;
  paymentTransactionId?: string;
}

export interface OrderResult {
  orderId: string;
  orderNumber: string;
  orderFormBlob: Blob;
  printFileBlob: Blob;
  printFilename: string;
}

/**
 * Process a completed order:
 * 1. Generate print-ready file with bleed & crop marks
 * 2. Generate order form PDF
 * 3. Create order record in DB
 * 4. Upload files to storage
 * 5. Update order with file URLs
 */
export async function processOrder(input: CreateOrderInput): Promise<OrderResult> {
  let printBlob: Blob;
  let printFilename: string;

  if (input.sourcePdfUrl) {
    // Use original vector PDF directly — best quality for sublimation
    const response = await fetch(input.sourcePdfUrl);
    if (!response.ok) throw new Error("Failed to fetch source PDF");
    printBlob = await response.blob();
    const { widthMm, heightMm } = parseDimensions(input.dimensionLabel);
    printFilename = `PADZONE_print_${widthMm / 10}x${heightMm / 10}cm_vector.pdf`;
  } else {
    // Fallback: generate PDF from raster image
    const printOptions: PrintFileOptions = {
      designImageSrc: input.designImageSrc,
      dimensionLabel: input.dimensionLabel,
      overlayText: input.customText,
      overlayFont: input.customFont,
      overlayAlign: input.customTextAlign as "left" | "center" | "right" | undefined,
    };
    const printResult = await generatePrintFile(printOptions);
    printBlob = printResult.blob;
    printFilename = printResult.filename;
  }

  // 2. Create order in DB (order_number is auto-generated by trigger)
  const totalPrice = input.unitPrice * input.quantity;

  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      order_number: "", // trigger will generate
      customer_name: input.customerName,
      customer_email: input.customerEmail || null,
      customer_phone: input.customerPhone,
      shipping_address: input.shippingAddress,
      design_id: input.designId || null,
      design_name: input.designName,
      design_image_url: input.designImageSrc.startsWith("data:") ? null : input.designImageSrc,
      dimensions: input.dimensionLabel,
      quantity: input.quantity,
      is_custom_design: input.isCustomDesign,
      custom_text: input.customText || null,
      custom_font: input.customFont || null,
      custom_text_align: input.customTextAlign || null,
      unit_price: input.unitPrice,
      total_price: totalPrice,
      status: "paid",
      payment_provider: "grow",
      payment_transaction_id: input.paymentTransactionId || null,
      paid_at: new Date().toISOString(),
    })
    .select()
    .single();

  if (orderError || !order) {
    throw new Error(`Failed to create order: ${orderError?.message}`);
  }

  // 3. Generate order form PDF
  const orderFormData: OrderFormData = {
    orderNumber: order.order_number,
    orderDate: new Date(order.created_at).toLocaleDateString("he-IL"),
    customerName: input.customerName,
    customerEmail: input.customerEmail,
    customerPhone: input.customerPhone,
    shippingAddress: input.shippingAddress,
    designName: input.designName,
    dimensions: input.dimensionLabel,
    quantity: input.quantity,
    unitPrice: input.unitPrice,
    totalPrice,
    isCustomDesign: input.isCustomDesign,
    customText: input.customText,
  };

  const orderFormBlob = generateOrderFormPDF(orderFormData);

  // 4. Upload files to storage
  const orderDir = `orders/${order.id}`;

  const [printUpload, formUpload] = await Promise.all([
    supabase.storage
      .from("order-files")
      .upload(`${orderDir}/${printFilename}`, printBlob, {
        contentType: "application/pdf",
        upsert: true,
      }),
    supabase.storage
      .from("order-files")
      .upload(`${orderDir}/order-form-${order.order_number}.pdf`, orderFormBlob, {
        contentType: "application/pdf",
        upsert: true,
      }),
  ]);

  // 5. Update order with file URLs
  const printFileUrl = printUpload.data?.path || null;
  const orderFormUrl = formUpload.data?.path || null;

  await supabase
    .from("orders")
    .update({
      print_file_url: printFileUrl,
      order_form_url: orderFormUrl,
    })
    .eq("id", order.id);

  return {
    orderId: order.id,
    orderNumber: order.order_number,
    orderFormBlob,
    printFileBlob: printBlob,
    printFilename,
  };
}
